# [cfg]
cfg.name = sanae
cfg.delay = 60
# color is R G B A
# [background]
background.file = 56884409_p0.jpg

# [hardware]
hardware.screen_width = 480
hardware.screen_height = 272

# [gui]
gui.show_cursor = 0

# [performance]
performance.max_fps = 1

# [time]
time.font = font.ttf
time.size = 48
time.color = 0x7ECF2AFF
time.colorOutline = 0xFFFFFFFF
time.outlineSize = 2
time.x = 285
time.y = 207

# [date]
date.font = font.ttf
date.size = 24
date.color = 0x7ECF2AFF
date.colorOutline = 0xFFFFFFFF
date.outlineSize = 2
date.x = 340
date.y = 179

# [fps]
fps.font = font.ttf
fps.size = 12
fps.color = 0x7ECF2AFF
fps.colorOutline = 0xFFFFFFFF
fps.outlineSize = 2
fps.x = 9
fps.y = 252

# [cpu_usage]
cpu_usage.font = font.ttf
cpu_usage.size = 24
cpu_usage.color = 0x7ECF2AFF
cpu_usage.colorOutline = 0xFFFFFFFF
cpu_usage.outlineSize = 2
cpu_usage.x = 15
cpu_usage.y = 1
cpu_usage.mode = 0
cpu_usage.progress_width = 80
cpu_usage.progress_height = 8
cpu_usage.progress_min = 0
cpu_usage.progress_max = 100

# [cpu_temp]
cpu_temp.font = font.ttf
cpu_temp.size = 24
cpu_temp.color = 0x7ECF2AFF
cpu_temp.colorOutline = 0xFFFFFFFF
cpu_temp.outlineSize = 2
cpu_temp.x = 16
cpu_temp.y = 100

# [memory_state]
memory_state.font = font.ttf
memory_state.size = 24
memory_state.color = 0x7ECF2AFF
memory_state.colorOutline = 0xFFFFFFFF
memory_state.outlineSize = 2
memory_state.x = 16
memory_state.y = 35
memory_state.mode = 1
memory_state.progress_width = 80
memory_state.progress_height = 8
memory_state.progress_min = 0
memory_state.progress_max = 100

# [storage_state]
storage_state.font = font.ttf
storage_state.size = 24
storage_state.color = 0x7ECF2AFF
storage_state.colorOutline = 0xFFFFFFFF
storage_state.outlineSize = 2
storage_state.x = 16
storage_state.y = 68
storage_state.mode = 2
storage_state.progress_width = 80
storage_state.progress_height = 8
storage_state.progress_min = 0
storage_state.progress_max = 100

#[ip_state]
ip_state.font = font.ttf
ip_state.size = 24
ip_state.color = 0x7ECF2AFF
ip_state.colorOutline = 0xFFFFFFFF
ip_state.outlineSize = 2
ip_state.x = 16
ip_state.y = 130
ip_state.interface = ens33