[cfg]
name = reisen
delay = 60
# color is R G B A
[background]
file = 40282422_p0.jpg

[hardware]
screen_width = 480
screen_height = 272

[gui]
show_cursor = 0

[performance]
max_fps = 1

[time]
font = font.ttf
size = 48
color = 0xFF1188FF
x = 28
y = 149

[date]
font = font.ttf
size = 24
color = 0xFF1188FF
x = 52
y = 200

[fps]
font = font.ttf
size = 12
color = 0xFF1188FF
x = 410
y = 250