# [cfg]
cfg.name = reisen
cfg.delay = 60
# color is R G B A
# [background]
background.file = 40282422_p0.jpg

# [hardware]
hardware.screen_width = 480
hardware.screen_height = 272

# [gui]
gui.show_cursor = 0

# [performance]
performance.max_fps = 1

# [time]
time.font = font.ttf
time.size = 48
time.color = 0xFF1188FF
time.x = 28
time.y = 149

# [date]
date.font = font.ttf
date.size = 24
date.color = 0xFF1188FF
date.x = 52
date.y = 200

# [fps]
fps.font = font.ttf
fps.size = 12
fps.color = 0xFF1188FF
fps.x = 410
fps.y = 250