# [cfg]
cfg.name = theme_reimi
cfg.delay = 60

# [hardware]
hardware.screen_width = 480
hardware.screen_height = 272

# [performance]
performance.max_fps = 1

# [time]
time.font = font.ttf
time.size = 48
time.color = 153,0,153,255
time.x = 275
time.y = 175

# [date]
date.font = font.ttf
date.size = 24
date.color = 153,0,153,255
date.colorOutline = 255,255,255
date.x = 340
date.y = 224

# [fps]
fps.font = font.ttf
fps.size = 12
fps.color = 153,0,153,255
fps.colorOutline = 255,255,255,255
fps.x = 410
fps.y = 255

# [background]
background.file = 7791442_p0.jpg
