# [cfg]
cfg.name = suwako_sanae
cfg.delay = 60

# [background]
background.file = Image_1758532072791.jpg

# [hardware]
hardware.screen_width = 480
hardware.screen_height = 272

# [gui]
gui.show_cursor = 0

# [performance]
performance.max_fps = 1

# [time]
time.font = font.ttf
time.size = 48
time.color = 0,153,153,255
time.x = 235
time.y = 27

# [date]
date.font = font.ttf
date.size = 24
date.color = 0,153,153,255
date.x = 267
date.y = 3

# [fps]
fps.font = font.ttf
fps.size = 12
fps.color = 0,153,153,255
fps.x = 413
fps.y = 253
