[cfg]
name = suwako_sanae

#60 frames
delay = 60

[background]
file = Image_1758532072791.jpg

[hardware]
screen_width = 480
screen_height = 272

[gui]
show_cursor = 0

[performance]
max_fps = 1

[time]
font = font.ttf
size = 48
#color = 0X89C4B8FF
color = 0X101010FF
x = 235
y = 27

[date]
font = font.ttf
size = 24
color = 0X101010FF
x = 267
y = 3

[fps]
font = font.ttf
size = 12
color = 0X101010FF
x = 413
y = 253
