# [cfg]
cfg.name = theme_elysia
cfg.delay = 60

# [hardware]
hardware.screen_width = 480
hardware.screen_height = 272

# [performance]
performance.max_fps = 1

# [time]
time.font = font.ttf
time.size = 48
time.color = 255,102,204,255
time.x = 281
time.y = 3
time.colorOutline = 0xFFFFFFFF
time.outlineSize = 2

# [date]
date.font = font.ttf
date.size = 24
date.color = 255,102,204,255
date.colorOutline = 255,255,255,255
date.outlineSize = 2
date.x = 343
date.y = 60

# [fps]
fps.font = font.ttf
fps.size = 12
fps.color = 255,102,204,255
fps.colorOutline = 0xFFFFFFFF
fps.outlineSize = 1
fps.x = 9
fps.y = 252

# [gui]
gui.show_cursor = 0

# [background]
background.file = elysia.jpg
