[cfg]
name = yakumo

#60 frames
delay = 60

[background]
file = 50296962_p0.png

[hardware]
screen_width = 480
screen_height = 272

[gui]
show_cursor = 0

[performance]
max_fps = 1

[time]
font = font.ttf
size = 48
color = 0xEEEEEEFF
x = 20
y = 100

[date]
font = font.ttf
size = 24
color = 0xEEEEEEFF
x = 42
y = 149

[fps]
font = font.ttf
size = 12
color = 0xEEEEEEFF
x = 410
y = 250
