# [cfg]
cfg.name = sanae
cfg.delay = 600

# [background]
background.dir = 105455920

# [hardware]
hardware.screen_width = 480
hardware.screen_height = 272

# [gui]
gui.show_cursor = 0

# [performance]
performance.max_fps = 15

# [time]
time.font = font.ttf
time.size = 48
time.color = 255,51,51,255
time.x = 290
time.y = 207

# [date]
date.font = font.ttf
date.size = 24
date.color = 255,51,51,255
date.x = 340
date.y = 179

# [fps]
fps.font = font.ttf
fps.size = 12
fps.color = 255,51,51,255
fps.x = 11
fps.y = 256
