# [cfg]
cfg.name = sanae
cfg.delay = 600

# [background]
background.dir = 105455920

# [hardware]
hardware.screen_width = 480
hardware.screen_height = 272

# [gui]
gui.show_cursor = 0

# [performance]
performance.max_fps = 15

# [time]
time.font = font.ttf
time.size = 48
time.color = 0xFF3333FF
time.x = 275
time.y = 207
time.colorOutline = 0xFFFFFFFF

# [date]
date.font = font.ttf
date.size = 24
date.color = 0xFF3333FF
date.x = 340
date.y = 179
date.colorOutline = 0xFFFFFFFF

# [fps]
fps.font = font.ttf
fps.size = 12
fps.color = 0xFF3333FF
fps.x = 11
fps.y = 256
fps.colorOutline = 0xFFFFFFFF
