[cfg]
name = sanae
delay = 600
# color is R G B A
[background]
file = 105455920

[hardware]
screen_width = 480
screen_height = 272

[gui]
show_cursor = 0

[performance]
max_fps = 15

[time]
font = font.ttf
size = 48
color = 0xEEEEEEFF
x = 290
y = 207

[date]
font = font.ttf
size = 24
color = 0xEEEEEEFF
x = 340
y = 179

[fps]
font = font.ttf
size = 12
color = 0xEEEEEEFF
x = 16
y = 261
